# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      - name: copy file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: '34.71.192.0'
          username: 'user'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '22'
          source: frontend-development/*
          target: /home/user

      - id: 'docker'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'instance-1'
          zone: 'us-central1-a'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 'cd /home/user/frontend-development && docker build -t react-app . && docker run -d -p 80:80 react-app'          
