# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'instance-1'
          zone: 'us-central1-a'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 'scp -r frontend-development user@34.71.192.0:~'

      - id: 'docker'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'instance-1'
          zone: 'us-central1-a'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 'cd /home/user/frontend-development && docker build -t react-app . && docker run -d -p 80:80 react-app'          
