# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-js-${{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -d -c -r public gs://my-gcs-react-bucket
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://my-gcs-react-bucket/**/*.html
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://my-gcs-react-bucket/js/*.js
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://my-gcs-react-bucket/css/*.css